# Generated by Django 6.0.3 on 2026-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bookingreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
