# Generated by Django 6.0.3 on 2026-04-30 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_bookingreservation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingreservation',
            name='notes',
        ),
        migrations.AddField(
            model_name='bookingreservation',
            name='attendance_type',
            field=models.CharField(choices=[('student', 'Student'), ('early-career', 'Early-career professional'), ('hiring-partner', 'Hiring partner'), ('community', 'Community member')], default='student', max_length=32),
        ),
        migrations.AddField(
            model_name='bookingreservation',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingreservation',
            name='organization',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingreservation',
            name='reference_code',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookingreservation',
            name='role_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('confirmed', 'Confirmed'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='bookingreservation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bookingreservation',
            name='guest_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
